# Generated by Django 6.1 on 2026-08-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('upi', 'UPI')], max_length=10)),
                ('provider', models.CharField(max_length=100)),
                ('network', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tracker.paymentsource')),
            ],
            options={
                'ordering': ['valid_until'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('expected_cashback', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('disputed', 'Disputed'), ('na', 'N/A')], default='pending', max_length=10)),
                ('transaction_date', models.DateField()),
                ('statement_month', models.CharField(blank=True, max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.offer')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.paymentsource')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
