# Generated by Django 6.1 on 2026-08-10 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPINumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upi_numbers', to='tracker.paymentsource')),
            ],
            options={
                'ordering': ['upi_id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='upi_numbers',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='tracker.upinumber'),
        ),
        migrations.CreateModel(
            name='DailyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_targets', to='tracker.paymentsource')),
            ],
            options={
                'ordering': ['-target_date'],
                'unique_together': {('source', 'target_date')},
            },
        ),
    ]
