# Generated by Django 6.1 on 2026-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_upinumber_transaction_upi_numbers_dailytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsource',
            name='daily_target',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DailyTarget',
        ),
    ]
