# Generated by Django 6.1 on 2026-08-11 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_paymentsource_daily_target_delete_dailytarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tracker.paymentsource'),
        ),
    ]
